"""Added ShoppingCartItems model

Revision ID: 31ba49eb2296
Revises: 35e20f88ec9a
Create Date: 2022-12-14 00:11:02.897438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31ba49eb2296"
down_revision = "35e20f88ec9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_cart_items",
        sa.Column("shopping_cart_items_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("shopping_cart_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shopping_cart_id"],
            ["shopping_cart.shopping_cart_id"],
        ),
        sa.PrimaryKeyConstraint("shopping_cart_items_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shopping_cart_items")
    # ### end Alembic commands ###
