"""Added Order model

Revision ID: 32ad356fb3ff
Revises: 46090f4bb964
Create Date: 2022-12-14 00:48:15.300291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32ad356fb3ff"
down_revision = "46090f4bb964"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], name="fk_person_id"),
        sa.ForeignKeyConstraint(["shipping_id"], ["address.id"], name="fk_address_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    # ### end Alembic commands ###
