"""Added ShoppingCartItems model

Revision ID: 46090f4bb964
Revises: f7e35e725a2c
Create Date: 2022-12-14 00:46:24.943312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46090f4bb964"
down_revision = "f7e35e725a2c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_cart_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("shopping_cart_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], name="fk_name_id"),
        sa.ForeignKeyConstraint(
            ["shopping_cart_id"], ["shopping_cart.id"], name="fk_shopping_cart_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shopping_cart_items")
    # ### end Alembic commands ###
