"""Added Person and ShoppingCart model

Revision ID: 4838387217d1
Revises: 1e4f2543947c
Create Date: 2022-12-14 00:04:19.473136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4838387217d1"
down_revision = "1e4f2543947c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("last_name", sa.String(length=32), nullable=True),
        sa.Column("phone_number", sa.String(length=16), nullable=True),
        sa.Column("email_address", sa.String(length=64), nullable=True),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.Column("billing_id", sa.Integer(), nullable=True),
        sa.Column("shopping_cart_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["billing_id"],
            ["address.address_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipping_id"],
            ["address.address_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shopping_cart_id"],
            ["shopping_cart.shopping_cart_id"],
        ),
        sa.PrimaryKeyConstraint("person_id"),
    )
    op.create_table(
        "shopping_cart",
        sa.Column("shopping_cart_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.person_id"],
        ),
        sa.PrimaryKeyConstraint("shopping_cart_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shopping_cart")
    op.drop_table("person")
    # ### end Alembic commands ###
