"""Added shipping/person id foreign keys to order table

Revision ID: 6784234d9194
Revises: 9282b727ae4c
Create Date: 2022-12-12 23:12:34.130363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6784234d9194'
down_revision = '9282b727ae4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shipping_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_shipping_id", 'address', ['shipping_id'], ['id'])
        batch_op.create_foreign_key("fk_person_id", 'person', ['person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint("fk_shipping_id", type_='foreignkey')
        batch_op.drop_constraint("fk_person_id", type_='foreignkey')
        batch_op.drop_column('shipping_id')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
