"""Added order table

Revision ID: 92145aa9f148
Revises: e54fee720571
Create Date: 2022-12-12 22:10:16.263504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92145aa9f148"
down_revision = "e54fee720571"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    # ### end Alembic commands ###
