"""Added shipping/billing foreign key columns to person table

Revision ID: 9282b727ae4c
Revises: 92145aa9f148
Create Date: 2022-12-12 23:00:14.111249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9282b727ae4c"
down_revision = "92145aa9f148"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_shipping_id", "address", ["shipping_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_billing_id", "address", ["billing_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_constraint("fk_shipping_id", type_="foreignkey")
        batch_op.drop_constraint("fk_billing_id", type_="foreignkey")

    # ### end Alembic commands ###
