"""Added Item model

Revision ID: a241d00fcd09
Revises: 4609aefcae6b
Create Date: 2022-12-14 00:40:41.655490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a241d00fcd09"
down_revision = "4609aefcae6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    # ### end Alembic commands ###
