"""Added orderitems and item table

Revision ID: a78971916c04
Revises: 6784234d9194
Create Date: 2022-12-13 19:40:05.909907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a78971916c04"
down_revision = "6784234d9194"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer),
        sa.Column("item_id", sa.Integer),
        sa.Column("quanity", sa.Integer),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items")

    # ### end Alembic commands ###
