"""Added item table

Revision ID: a8b697136e0a
Revises: a78971916c04
Create Date: 2022-12-13 20:25:22.023891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8b697136e0a"
down_revision = "a78971916c04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quantity", sa.Integer(), nullable=True))
        batch_op.drop_column("quanity")
        batch_op.drop_column("item_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("item_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("quanity", sa.INTEGER(), nullable=True))
        batch_op.drop_column("quantity")

    op.drop_table("item")
    # ### end Alembic commands ###
