"""Added OrderItems model

Revision ID: cebdcb7aca30
Revises: 32ad356fb3ff
Create Date: 2022-12-14 00:48:55.633389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cebdcb7aca30"
down_revision = "32ad356fb3ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["item.id"], name="fk_name_id"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], name="fk_order_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items")
    # ### end Alembic commands ###
