"""Added Order model

Revision ID: d3cd8c7dbb9b
Revises: 4838387217d1
Create Date: 2022-12-14 00:07:06.616592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3cd8c7dbb9b"
down_revision = "4838387217d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["shipping_id"],
            ["address.address_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    # ### end Alembic commands ###
