"""Added ShoppingCart and ShoppingCartItems tables

Revision ID: da2acd720698
Revises: b7ca20f11ec4
Create Date: 2022-12-13 20:54:58.569765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da2acd720698"
down_revision = "b7ca20f11ec4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shopping_cart_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shopping_cart_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shopping_cart_id"],
            ["shopping_cart.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("shopping_cart_items")
    op.drop_table("shopping_cart")
    # ### end Alembic commands ###
