"""Added ShoppingCart model

Revision ID: f2f99b2564b8
Revises: 1e4f2543947c
Create Date: 2022-12-13 23:55:02.364622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2f99b2564b8"
down_revision = "1e4f2543947c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_cart",
        sa.Column("shopping_cart_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.person_id"],
        ),
        sa.PrimaryKeyConstraint("shopping_cart_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shopping_cart")
    # ### end Alembic commands ###
