"""Added item_id to order_items table

Revision ID: f55ea7d154c1
Revises: da2acd720698
Create Date: 2022-12-13 20:56:30.698984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f55ea7d154c1"
down_revision = "da2acd720698"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("item_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_item_id", "item", ["item_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_constraint("fk_item_id", type_="foreignkey")
        batch_op.drop_column("item_id")

    # ### end Alembic commands ###
