"""Added Person and ShoppingCart models

Revision ID: f7e35e725a2c
Revises: e3195166a27b
Create Date: 2022-12-14 00:42:59.396639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7e35e725a2c"
down_revision = "e3195166a27b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("last_name", sa.String(length=32), nullable=True),
        sa.Column("phone_number", sa.String(length=16), nullable=True),
        sa.Column("email_address", sa.String(length=64), nullable=True),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.Column("billing_id", sa.Integer(), nullable=True),
        sa.Column("shopping_cart_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["billing_id"], ["address.id"], name="fk_address_id"),
        sa.ForeignKeyConstraint(["shipping_id"], ["address.id"], name="fk_address_id"),
        sa.ForeignKeyConstraint(
            ["shopping_cart_id"], ["shopping_cart.id"], name="fk_shopping_cart_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shopping_cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], name="fk_person_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shopping_cart")
    op.drop_table("person")
    # ### end Alembic commands ###
