"""Added Item model

Revision ID: f899642455b2
Revises: 9c03f5737c8a
Create Date: 2022-12-13 23:49:20.360317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f899642455b2"
down_revision = "9c03f5737c8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    # ### end Alembic commands ###
