"""Added shipping/billing id to person table

Revision ID: fadd65d95b96
Revises: f55ea7d154c1
Create Date: 2022-12-13 20:58:23.907852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fadd65d95b96"
down_revision = "f55ea7d154c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shipping_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("billing_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_shipping_id", "address", ["shipping_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_billing_id", "address", ["billing_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_constraint("fk_shipping_id", type_="foreignkey")
        batch_op.drop_constraint("fk_billing_id", type_="foreignkey")
        batch_op.drop_column("billing_id")
        batch_op.drop_column("shipping_id")

    # ### end Alembic commands ###
